### PR TITLE
[WIP] Added basic draft of contributors document.

### PR DESCRIPTION
**Pull request by tricoder42**
It would make thinks easier if we have a person (or two) responsible for each language. There can be many contributors on Crowdin, but there should be always a person who can proofread all translations and correct any errors.

### CODE REVIEW

**Comment by tricoder42** [comment]
**Note:** Please don't merge until it's ready

**Comment by tricoder42** [comment]
The list of translators for each language can be filtered here: https://crowdin.com/project/django-girls-tutorial/settings#members (Managers and owners have access to all languages)

**Comment by bmispelon** [comment]
(I added the `[WIP]` at the beginning to mark this as a work in progress, please remove it and let us know when you want a review/merge)

**Comment by rapoulson** [comment]
Nice :tada: , I'm inclined to call the main translators "ambassadors" instead of "managers", it just seems a little more welcoming and cohesive with the friendly tone we try to maintain. What do you think?

**Comment by tricoder42** [comment]
Yes, definitely :clap:  I should learn how to use emojis everywhere, because your responses are more cheerful than mine :smile:

**Comment by olasitarska** [comment]
Hey, will you merge it whenever you feel like it's ready? :)

**Comment by tricoder42** [comment]
We probably should. This is going to be ongoing process.

**Comment by tricoder42** [comment]
I'll discuss it with @rapoulson soon and decide what to do with languages where we don't know how is proofreading and translating...

**Comment by rapoulson** [comment]
Totally! :+1: I feel like we should just clean up and standardize the formatting and then under the languages we don't know, maybe we should put something like, "We don't have contact information for a current translator for this language. Interested in becoming one? Drop us a note at translations@djangogirls.org!" Or something like that.

**Comment by patjouk** [comment]
Hi !
How is the PR going? It looks pretty cool :+1: 
Just tell me if I can merge it and I'll update it with the missing translators info :wink:

**Comment by tricoder42** [comment]
Not very good, to be honest :/ People usually ask to join Crowdin, translate or proofread tutorial, but there's rarely any retention once the work is done or the workshop is over. Some languages have so many people assigned to it, that I don't even know who manages it.

Final proofreader usually tell us that translations are ready on Slack. So, whole process is very dynamic at the moment and this static document doesn't capture it at all.

Not sure how to deal with it though :)

**Comment by patjouk** [comment]
Thanks for the update :heart: 
I'll ask the new translations managers to survey who is doing what on Crowdin.
Do you think is still a good idea to have this page or that it will be to complicated to maintain?

**Comment by olasitarska** [comment]
ping ping @tricoder42 :)

**Comment by tricoder42** [comment]
Well, I think both: It's a good idea to have this page, but it's complicated to maintain :/

It's useful when you publish update of source document and you want to ping all translators/proofreaders to fix changes in their language too. Right now we can't do that and Crowding is behind Github repository...

However, once we sent invitation to our volunteers, we loose any control over them. We might get a list of proofreaders, because we can find them in Crowdin. It's definitely difficult to get a list of active translators, as some of them seem to be active for a limited time only.

Any ideas? :)

Otherwise I would merge it as it is (maybe list only published languages) and then update it when the time comes...

**Comment by olasitarska** [comment]
Maybe let's rely on translators updating this page themselves?

**Comment by tricoder42** [comment]
Sure, that's possible too :+1:

In that case we can omit this document. Re-open if needed ;)

**Pull request closed without merging**
